# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: wbooks-api
  password: wbooks-api

development:
  <<: *default
  database: wbooks-api_development

test:
  <<: *default
  database: wbooks-api_test

production:
  <<: *default
  database: wbooks-api_production
  username: wbooks-api
  password: <%= ENV['WBOOKS-API_DATABASE_PASSWORD'] %>
