# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aca23d1befc693835c554a57e4b980ca3cd1d74ea145e07fea6357e1038c672e748e4201bf427ef889053eb56436a76e145dc0167dd17ca55c6a841097d9cb9a
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_password:  <%= ENV["MAILER_PASSWORD"] %>
  mailer_address:  <%= ENV["MAILER_ADDRESS"] %>
  mailer_port:  <%= ENV["MAILER_PORT"] %>
  mailer_user_name:  <%= ENV["MAILER_USER_NAME"] %>




test:
  secret_key_base: f4b12303cff46bb98aad2ddc10cd33e0dc19d35837c2a2e6e50828805be404c60d667ad666007e5d098b48bb72405ea789d44eeedc4c392dfc0c739512bb45e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
